[dependencies]
base = "0.14.3"
new-base = "0.3.0"
http-types = "1.0.1"
base64 = "1.0.0"
xtended-numbers = "0.3.1"
itertools = "0.2.2"
ecdsa = "1.0.0"
json = "1.0.1"

[package]
name = "openchat-bot-sdk"
version = "0.0.6"
description = "A library for creating OpenChat bots with defined types and http handlers"
repository = "https://github.com/edjcase/motoko_oc_bot_sdk"
keywords = ["openchat", "sdk", "bot"]
license = "MIT"

[dev-dependencies]
test = "2.1.0"
