[dependencies]
base = "0.14.1"
http-types = "1.0.1"
base64 = "1.0.0"
xtended-numbers = "0.3.1"
itertools = "0.2.2"
ecdsa = "https://github.com/edjCase/motoko_ecdsa#master@17c7c3289cc6a8f39e5679b2db5fe07348c646bf"
json = "1.0.1"

[package]
name = "openchat-bot-sdk"
version = "0.0.1"
description = "A library for creating OpenChat bots with defined types and http handlers"
repository = "https://github.com/edjcase/motoko_oc_bot_sdk"
keywords = ["openchat", "sdk", "bot"]
license = "MIT"

[dev-dependencies]
test = "2.1.0"
